### ISSUE TITLE
Sign-to-contract support in DBCs and signle-use-seals

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/client_side_validation#53]
Prerequisites:

- [ ] S2C standard https://github.com/LNP-BP/LNPBPs/pull/118
- [ ] S2C commitments in Schnorr signatures inside `secp256k1` library.
       Implementation WIP: https://github.com/LNP-BP/secp256k1/tree/schnorr-commitments
       Previous work: https://github.com/bitcoin-core/secp256k1/pull/589
- [ ] S2C commitment scheme for MuSig2 and its implementation in `secp256k1-zkp`
- [ ] Rust code for ECDSA S2C from `secp256k1-zkp`
- [ ] Rust code for Schnorr S2C from `secp256k1`
