### ISSUE TITLE
Refactor strict_encoding crate

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/client_side_validation#97]
The original intent of `strict_encoding` was to provide encoding standard for the client-side-validation. That is why the crate is a part of this repository and used everywhere inside RGB and AluVM.

However, it appeared that the crate has become much more widely used, including commercial projects much outside of the scope of the client-side-validation. That happened due to the fact that in rust there are no good binary compact encodings guaranteeing determinism in data.

Widespread use of `strict_encoding` creates pressure for adding more dependencies and types to it, since rust foreign type policies prohibits derivation of strict encoding traits on other dependencies downstream. While the new dependencies are optional, it still blows up codebase and requires permanent releases of new version.

On the other hand, client-side-validation requirements to the encoding are quite specific; for instance, we use bitcoin consensus encoding in many places, and this encoding is not consistant nor provides the same approach as encoding for other types. 

So basically, it should not be advised to use strict encoding for anything else than client-side-validation and add more types here. Nevertheless, it is really hard to prevent that, especially taking into account existing adoption of the crate.

The solution I propose is the following:
- [ ] Fork the strict encoding crate into two different crates with different purposes: `strict_encoding` and `confined_encoding`;
- [ ] Move strict encoding outside of this repository, to github.com/Internet2-wg/ (where it will be used for instance by AluVM);
- [ ] Migrate all client-side-validation, BP Core and RGB Core libraries to use exclusively `confined_encoding`;
- [ ] Let any other project use `strict_encoding` (including descriptor wallet etc);
- [ ] Remove use of any custom encodings (like bitcoin consensus etc) from the `strict_encoding`;
- [ ] Remove TLV support from the `confined_encoding`.

This will restrict use of new crate `confined_encoding` to client-side-validation consensus *only*. Any non-consensus code (including descriptor wallet etc) MUST NOT use `confined_encoding`. The `confined_encoding` must be ossified and new types must not be added to it.

**Comment by dr-orlovsky** [comment]
I did a PR #100 implementing most of the tasks. It removes ~6000 lines of code, which will simplify maintenance of this consensus-critical repository. It also removes plenty of optional dependencies, thus significantly reducing CI times
